### ISSUE TITLE
Xamarin from how apply magic Gradient with CSS on ToolBar and Status Bar

### ISSUE THREAD

**Issue by ghotekarduryo** [mgierlasinski/MagicGradients#116]
Xamarin from how apply magic Gradient with CSS on ToolBar and Status Bar

**Comment by mgierlasinski** [comment]
Hi @ghotekarduryo, `GradientView` is pure Xamarin.Forms control but toolbar of `NavigationPage` is native for each platform. Because of that you can't simply use Magic Gradient as a background. However you can play around with `TitleView` and use `Grid` with `GradientView` and some `Label` as it's content. 

[Displaying Views in the Navigation Bar](https://docs.microsoft.com/en-us/samples/xamarin/xamarin-forms-samples/navigation-titleview/)

Alternatively you can just hide default toolbar with attached property `NavigationPage.HasNavigationBar="false"` and create your custom toolbar from Xamarin.Forms controls. That gives you way more flexibility but you have to handle navigation stack, back arrow etc. yourself.

Custom AppBar was planner for Xamarin.Forms but it has been cut, it may appear in XamarinCommunityToolkit.
https://github.com/xamarin/Xamarin.Forms/issues/10774
