### ISSUE TITLE
Magic Button control

### ISSUE THREAD

**Issue by bbenetskyy** [mgierlasinski/MagicGradients#118]
We have a lot of requests for adding our own `MagicButton` because for achieving button with gradient background we making the same structure each time:
```c#
Frame
   |
   |-> Grid
            |
            |-> GradientView
            |-> Button
```

## API Changes

**N/A**

## New Built-in Control in NuGet

`MagicButton` control in `MagicGradients.Controls` namespace with next bindable properties:

| Property | Type | Converter |
|---|---|---|
| Text | string | 
| FontSize | double | Xamarin.Forms.FontSizeConverter | 
| FontFamily | string | 
| TextColor | Xamarin.Forms.Color | 
| GradientSource | MagicGradients.IGradientSource | 
| Command | System.Windows.Input.ICommand | 
| CornerRadius | float | 

## Update existing ReadMe.md file

We need to provide short information about new existed control

## Add new Blog Post

We need to have a new blog post about new control with more details and useful examples

## Add new video

Good to have also a video at YouTube (with link to it in readme) where will be described a new control and useful examples

**Comment by mgierlasinski** [comment]
What if you could make Content for Button instead of Text? Like UWP button? MagicButton xaml:
```
<ContentView>
    <ContentView.ControlTemplate>
        <ControlTemplate>
            <Frame>
                <Grid>
                    <magic:GradientView />
                    <Button />
                    <ContentPresenter />
                </Grid>
            </Frame>
        </ControlTemplate>
    </ContentView.ControlTemplate>
</ContentView>
```
Usage:
```
<MagicButton Content="Only text" /> -> this will convert string to <Label Text="Only text" />
```
or
```
<MagicButton>
    <Grid>
         Other crazy stuff here
    </Grid>
</MagicButton>
```
In that case you would have to revert Button to be ContentView, not Frame (sorry :( )

See:
https://github.com/mgierlasinski/MagicGradients/blob/feature/gradient-animation/PlaygroundLite/PlaygroundLite/Controls/AnimationClip.xaml

**Comment by bbenetskyy** [comment]
I think this is not common for Xamarin.Forms developers(as it is for UWP Dev's) and better create one more control a `MagicFrame` or `MagicControl` with a structure you describe above and give users the possibility to select what they want: just button with gradients or a gradient control with anything inside it 😇

**Comment by mgierlasinski** [comment]
You would be surprised how many Xamarin.Forms developers came from other Xaml-world and they miss it's templating and flexibility :)

What is the reason for having `MagicFrame` which is a `GradientView` inside `Frame`? 

Xamarin.Forms is changing to be more template-focused and have properties more generic. Examples? Sure:

`BackgroundColor` -> `Background` which is `Brush`, so you can put there color, image, gradient etc., not only color.
`Image` with `ImageSource` -> has been refactored to use anything that is of type `ImageSource`.

This was philosophy of Xaml since the beginning, in WPF, Windows Phone, now with UWP and Uno. Problem with Forms is that they were trying to map Xaml controls into native controls 1:1 - so button can have only text or icon because Android and iOS allows only that.

What's wrong with using button such way:
<MagicButton Content="I'm simple button" />

It's just matter of naming, you have it instead of:
<MagicButton Text="I'm simple button" />

but it gives you power to set anything as Content, not only simple text. You want icon on the left, right, top, bottom - sure, why not.

**Comment by bbenetskyy** [comment]
Large Button used `TestProperty` a small one used `Content`:

(BattleTestPage.xaml
```xaml
<controls:MagicButton
                Command="{Binding ClickCommand}"
                CornerRadius="10"
                FontSize="16"
                GradientSource="{Binding GradientSource}"
                HeightRequest="100"
                Text="MagicGradients Large Button"
                TextColor="{Binding TextColor}" />
            <controls:MagicButton
                Command="{Binding ClickCommand}"
                CornerRadius="10"
                FontSize="16"
                GradientSource="{Binding GradientSource}"
                HeightRequest="50"
                HorizontalOptions="Center"
                WidthRequest="150">
                <Grid>
                    <Label
                        Margin="10"
                        HorizontalTextAlignment="Start"
                        Text="Small"
                        TextColor="{Binding TextColor}"
                        VerticalOptions="End" />
                    <Label
                        Margin="10"
                        HorizontalTextAlignment="End"
                        Text="Button"
                        TextColor="{Binding TextColor}"
                        VerticalOptions="Start" />
                </Grid>
            </controls:MagicButton>
```

![image](https://user-images.githubusercontent.com/8330262/93672438-1d879d80-faab-11ea-8a95-c5286ae51901.png)
